//
// Created by DEBUG on 4/13/2020.
//

#include "TestException.h"

void testExceptionCall()
{
    exceptionCall("testExceptionCall", "test crash");
}